# Writen by: Oscar Bergström
# https://github.com/OSCARJFB

#	in debug mode. 
main: main.c
	cc main.c -g validateBrackets.c validateComments.c validateFunctions.c validateNaming.c validateVariables.c -o main.o 

clean:
	rm -rf *.o